version: '3'

services:
  nginx_proxy:
    depends_on:
      - server
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    restart: "on-failure"
    expose:
      - 5000
    volumes:
      - './:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true